### ISSUE TITLE
Impement the storage for fitted chains

### ISSUE THREAD

**Issue by nicl-nno** [nccr-itmo/FEDOT.Web#24]
Сейчас в логике загрузки и сохранения обученных chain-ов стоит заглушка (см. https://github.com/nccr-itmo/FEDOT.Web/blob/composer-api/app/api/chains/service.py). Поэтому на все запросы возвращается одинаковый ответ.

Необходимо реализовать хранение chain-ов в какой-либо БД.

Выбор архитектурного решения тут связан с issue #5 но для начала можно реализовать что-то простое (как прототип).

**Comment by Sash0check** [comment]
Предлагаю mongo)

**Comment by nicl-nno** [comment]
Почему бы и нет, вроде с фласком он легко объединяется.

Ты предлагаешь mongo именно для chain-ов или в целом для всех данных (перечней showscase, историй оптимизации и т.п.)?

**Comment by Sash0check** [comment]
Да, для всех данных, кроме пользовательской информации)

**Comment by nicl-nno** [comment]
ок

**Comment by nicl-nno** [comment]
#27
