### ISSUE TITLE
MONGO_URI Error on running main.py

### ISSUE THREAD

**Issue by hemangjoshi37a** [nccr-itmo/FEDOT.Web#76]
![Screenshot from 2021-09-19 09-31-11](https://user-images.githubusercontent.com/12392345/133915113-3e419c52-55ec-48e2-aeb2-93fa8d93e510.png)

**Comment by nicl-nno** [comment]
Hi!

Please check the environmental variable MONGO_CONN_STRING exists.
The following command can be used
`
echo $MONGO_CONN_STRING
`

The value should be 'mongodb://127.0.0.1:27017/test_db?compressors=zlib'

**Comment by hemangjoshi37a** [comment]
> Hi!
> 
> Please check the environmental variable MONGO_CONN_STRING exists. The following command can be used `echo $MONGO_CONN_STRING`
> 
> The value should be 'mongodb://127.0.0.1:27017/test_db?compressors=zlib'

Thanks
